---
site_name: Armory
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Configuration Files: configuration_files.md
  - Baseline Models: baseline_models.md
  - Datasets: datasets.md
  - Adversarial Datasets: adversarial_datasets.md
  - Dataset Licensing: dataset_licensing.md
  - Docker: docker.md
  - Metrics: metrics.md
  - Scenarios: scenarios.md
  - Command Line: command_line.md
  - External Repos: external_repos.md
  - FAQs: faqs.md
  - Contributing: contributing.md
theme: readthedocs
