---
name: ğŸ’» Stand Alone Tests

on:
  workflow_call:


jobs:
  stand-alone-test:
    name: ğŸ“ Stand Alone Test Suite
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: ğŸ„ Got git?
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ Switch Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: ğŸŒ± Setup Test Enviroment
        run: |
          python -m pip install --upgrade pip

      - name: âš™ï¸ Installing Armory
        shell: bash
        run: |
          pip install --no-compile --editable '.[developer,engine,pytorch,tensorflow]'
          armory configure --use-defaults

      - name: ğŸ¤ Run Host Configuration Tests
        env:
          PYTEST_PARAMS: --exitfirst --suppress-no-test-exit-code
        shell: bash
        run: |
          echo "Testing Python Version: ${{ matrix.python-version }}"
          pytest -c pyproject.toml -s ./tests/unit/test_configuration.py

      - name: ğŸ¤ Run Stand Alone No-Docker & Unit Tests
        env:
          PYTEST_PARAMS: --exitfirst --suppress-no-test-exit-code
        shell: bash
        run: |
          pytest -c pyproject.toml -m "not docker_required and unit" ./tests/

      - name: ğŸ¤ Run Stand Alone End-to-End Tests
        env:
          PYTEST_PARAMS: --exitfirst --suppress-no-test-exit-code
        shell: bash
        run: |
          pytest -c pyproject.toml -s ./tests/end_to_end/test_no_docker.py
